### ISSUE TITLE
RSVP: Initial Meetup — January 16, 2014

### ISSUE THREAD

**Issue by terinjokes** [sushijs/san-francisco-ca-usa#1]
**When**: January 16, 2014 @ 6pm
**Where**: [Kama Sushi, 294 9th Street](https://plus.google.com/109824712801131168375/about?gl=us&hl=en)
**Who**: San Francisco JavaScript developers, enthusiasts and people who love them
**Why**: Uhm, I really like sushi.

---

<table style="border-collapse: collapse">
  <tr>
    <td>
      <img src="http://www.gravatar.com/avatar/d32635f156e30c2f863ec95af93aef18.jpg?s=150">
    </td>
    <td>
      <p><em>SushiJS: Bringing together San Francisco JavaScript developers through sushi and conversation</em></p>
    </td>
  </tr>
</table>

---

Attendees are expected to follow the [Code of Conduct](https://github.com/sushijs/san-francisco-ca-usa/blob/master/CODEOFCONDUCT.md)

**Comment by terinjokes** [comment]
January 16th around 6ish work for me. What's it looking like for everyone else?

/cc @dotjs @lakenen @mattbasta @jden

**Comment by mattbasta** [comment]
Is there a venue picked out?

**Comment by terinjokes** [comment]
@mattbasta Not yet, no

**Comment by junosuarez** [comment]
Possible venue: [Kama Sushi](http://www.yelp.com/biz/kama-sushi-soma-san-francisco-4)

**Comment by terinjokes** [comment]
I've never been there, but looks good to me. Any objections?

**Comment by paulirish** [comment]
seems good.

**Comment by indexzero** [comment]
I'm down. I leave on Jan 19 though!

**Comment by connor** [comment]
:sushi:

**Comment by gwynne** [comment]
I might not be in town that long... I can't promise being around after the 15th.

**Comment by lakenen** [comment]
In!

**Comment by ljharb** [comment]
In!

**Comment by terinjokes** [comment]
Is everyone (excepting @gwynne :frowning:) good with Kama Sushi, January 16th @ 6pm then?

**Comment by terinjokes** [comment]
Editing the original post

**Comment by terinjokes** [comment]
Done. BTW, I have some stickers.

**Comment by gwynne** [comment]
Update - I will indeed be around!

**Comment by mattbasta** [comment]
I'll do it!

**Comment by jmorrell** [comment]
I'm in!

**Comment by cheeaun** [comment]
:+1: in!

**Comment by junosuarez** [comment]
@terinjokes has anyone called the place to let them know?

**Comment by terinjokes** [comment]
I did

**Comment by terinjokes** [comment]
This thing is happening tonight. See you there!

**Comment by gwynne** [comment]
@terinjokes I may be a bit early, will you be there? ^^;

**Comment by terinjokes** [comment]
I'd been planning to be a few minutes early.

**Comment by cagerton** [comment]
This looks cool. I'm in.

**Comment by terinjokes** [comment]
Thanks everyone for coming out.

If you came to SushiJS, or even if you didn't come to SushiJS, please spend 5 minutes filling out the [SushiJS Feedback Form](https://docs.google.com/forms/d/1MDz-hJBCpITw2m0UhOo7y6xsR3vaa8qm4s0iQStSOJA/viewform) to help me improve this meetup moving forward.

Thanks!

**Comment by mikeal** [comment]
wish I knew about this yesterday, i would have gone :(

next time you should get this up on node-meatspace http://nodemeatspace.com/

**Comment by lakenen** [comment]
There will be more (right @terinjokes?)!

**Comment by terinjokes** [comment]
@mikeal I didn't know about it nor knode until the other issue was opened. Will add.

@lakenen Yes

**Comment by terinjokes** [comment]
Thanks for the feedback.

I'll be sure to get more tables next time, which should resolve the crampedness of this first meeting. I didn't think more than 10 people would show!

I'll also work to make RSVPs more visible. As far as I know, this hasn't been brought up in our sibling meetups that also us GitHub issues for discussions and RSVPs. (/cc @jden)

**Comment by junosuarez** [comment]
@terinjokes for something like this where the format is seated & requires a more specific headcount (rather than just piling up at a bar), it's reasonable to require an RSVP. I still think it could work over GH Issues.

**Comment by terinjokes** [comment]
@jden I agree, first meeting problems.
