### ISSUE TITLE
Add to knode/meetups

### ISSUE THREAD

**Issue by junosuarez** [sushijs/san-francisco-ca-usa#2]
knode has a great list or resources for people who want to participate in and organize meetups.

knode/meetups is a repository of meetup formats - essentially the readmes of the meetups. since sushijs has a particularly unique format, it should definitely be added!

https://github.com/knode/meetups

further, @mikeal's node-meatspace repo was recently folded into knode. this is a great place to list specific instances of events - a git-driven community calendar, if you will. as new events are scheduled, it would be awesome to add them at https://github.com/knode/node-meatspace

**Comment by terinjokes** [comment]
Resolved with https://github.com/knode/meetups/pull/21
