### ISSUE TITLE
RSVP: February 2014 Meetup

### ISSUE THREAD

**Issue by terinjokes** [sushijs/san-francisco-ca-usa#3]
We had a great turnout last month, and I made sure to reserve more room for this month.

---

**When**: February 19, 2014 @ 6pm
**Where**: [Kama Sushi, 294 9th Street](https://plus.google.com/109824712801131168375/about?gl=us&hl=en)
**Who**: San Francisco JavaScript developers, enthusiasts and people who love them
**Why**: Uhm, I really like sushi. And it seems you guys like sushi too.

---

<table style="border-collapse: collapse">
  <tr>
    <td>
      <img src="http://www.gravatar.com/avatar/d32635f156e30c2f863ec95af93aef18.jpg?s=150">
    </td>
    <td>
      <p><em>SushiJS: Bringing together San Francisco JavaScript developers through sushi and conversation</em></p>
    </td>
  </tr>
</table>

---

Attendees are expected to follow the [Code of Conduct](https://github.com/sushijs/san-francisco-ca-usa/blob/master/CODEOFCONDUCT.md)

**Comment by btford** [comment]
:sushi:

**Comment by lakenen** [comment]
Same place? Tuesday, 2/11?

**Comment by terinjokes** [comment]
I'm fine with Tuesday at the same place. There was some feedback to make it a tad bit later, would 6:30 work?

**Comment by mikeal** [comment]
I can't do Tuesday, can do Monday though, but don't change on my account.

**Comment by terinjokes** [comment]
I wouldn't be against Monday if that ends up working better.

**Comment by lakenen** [comment]
I can do Monday as well!

**Comment by btford** [comment]
I can't do mon or tues next week; wed or thurs work for me.

**Comment by terinjokes** [comment]
:no_good:

**Comment by terinjokes** [comment]
I'm good with any day next week except Thursday

**Comment by terinjokes** [comment]
By royal decree, I think I'm just going to set this for Wednesday 2/19, same place as last month at 6. Object now if you want.

**Comment by btford** [comment]
:+1:

**Comment by terinjokes** [comment]
Reserved, made sure to get more tables than we did last time. :)

**Comment by chromakode** [comment]
:dancers:

**Comment by lakenen** [comment]
:+1:

**Comment by terinjokes** [comment]
Day of bump. See you all there.

**Comment by terinjokes** [comment]
Thanks for coming out!

**Comment by btford** [comment]
:heart:
