### ISSUE TITLE
April 16, 2014

### ISSUE THREAD

**Issue by terinjokes** [sushijs/san-francisco-ca-usa#4]
Switching registration to Tito this month, to get a more accurate count for reservations. Please register: https://ti.to/sushijs/sf-april2014

---

**When**: April 16, 2014 @ 6pm
**Where**: [Kama Sushi, 294 9th Street](https://plus.google.com/109824712801131168375/about?gl=us&hl=en)
**Who**: San Francisco JavaScript developers, enthusiasts and people who love them
**Why**: Uhm, I really like sushi. And it seems you guys like sushi too.
**Register**: https://ti.to/sushijs/sf-april2014

---

<table style="border-collapse: collapse">
  <tr>
    <td>
      <img src="http://www.gravatar.com/avatar/d32635f156e30c2f863ec95af93aef18.jpg?s=150">
    </td>
    <td>
      <p><em>SushiJS: Bringing together San Francisco JavaScript developers through sushi and conversation</em></p>
    </td>
  </tr>
</table>

---

Attendees are expected to follow the [Code of Conduct](https://github.com/sushijs/san-francisco-ca-usa/blob/master/CODEOFCONDUCT.md)

**Comment by btford** [comment]
:sushi:

**Comment by mikeal** [comment]
that logo is amazing ;)

**Comment by junosuarez** [comment]
Can I propose a date prior to 4/11? I fly out on that date. Say, Wednesday April 9th?

**Comment by terinjokes** [comment]
I think having a consistent day each month is easier in the long run than changing it every month (and way easier to organize). I'm happy to get sushi with you separately, of course. :smile:

**Comment by chromakode** [comment]
:yum:

**Comment by terinjokes** [comment]
I'm leaving the tickets open until Monday.

**Comment by terinjokes** [comment]
Day of bump. Hope to see all of you this evening.

**Comment by btford** [comment]
I will be there. :sparkles: :sushi: :sparkles:

**Comment by parshap** [comment]
I'll be there! :sushi:

**Comment by mikeal** [comment]
I'll be there :) is there any room for more? a friend is in town and might want to come.

**Comment by techdubb** [comment]
I'm not going to be able to make it. @mikeal, feel free to take my spot. :smile:

**Comment by cstumph** [comment]
I'll be there.

**Comment by johnedgar** [comment]
Y'all eat so early in SF. I'll try and make it, hectic day but would like to see you all. 🍣

**Comment by terinjokes** [comment]
Thanks all for coming out. Hope to see y'all again next month.
