### ISSUE TITLE
Fishless abandoned rice balls make @btford sad

### ISSUE THREAD

**Issue by chromakode** [sushijs/san-francisco-ca-usa#6]
Steps to reproduce:
1. Eat the :fish: off of :sushi:, leaving the :rice_ball:.
2. @btford will become sad.

In past cases, this situation has resolved itself by @btford eating the remaining :rice_ball: .

Suggested fixes:
1. Patch the code of conduct to prohibit abandoning :rice_ball:s.
2. Patch the code of conduct to require @btford to eat any abandoned :rice_ball:s.
3. Order sashimi instead.

**Comment by btford** [comment]
+1

**Comment by terinjokes** [comment]
I patched the Code of Conduct two hours ago.

**Comment by btford** [comment]
:dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers: :dancers:

**Comment by L1fescape** [comment]
Also remember :sunglasses: next time in the off chance you get the spot with the sun.

**Comment by btford** [comment]
@akenn ++; we should have a best practices section.

**Comment by mikeal** [comment]
i don't think we need to prematurely optimize the sushi eating process when the conversion rate of rice with each piece of fish is above 90%. most people would kill for a 10% churn rate :)

**Comment by junosuarez** [comment]
maybe just order chirashi or sashimi? #bestpractices
