### ISSUE TITLE
International Sushi Day: June 18, 2014

### ISSUE THREAD

**Issue by terinjokes** [sushijs/san-francisco-ca-usa#9]
**When**: June 18, 2014 @ 6pm
**Where**: [Kama Sushi, 294 9th Street](https://plus.google.com/109824712801131168375/about?gl=us&hl=en)
**Who**: San Francisco JavaScript developers, enthusiasts and people who love them
**Why**: It's International Sushi Day! (and also the third Wednesday of the month, go figure)
**Register**: http://www.meetup.com/sushijs-sf/events/184585402/

---

<table style="border-collapse: collapse">
  <tr>
    <td>
      <img src="http://www.gravatar.com/avatar/d32635f156e30c2f863ec95af93aef18.jpg?s=150">
    </td>
    <td>
      <p><em>SushiJS: Bringing together San Francisco JavaScript developers through sushi and conversation</em></p>
    </td>
  </tr>
</table>

---

Attendees are expected to follow the [Code of Conduct](https://github.com/sushijs/san-francisco-ca-usa/blob/master/CODEOFCONDUCT.md)

**Comment by junosuarez** [comment]
+1  I'm in.

**Comment by btford** [comment]
im probably in

**Comment by nquinlan** [comment]
I'm in.

**Comment by terinjokes** [comment]
Register link active.

**Comment by btford** [comment]
:sushi:

**Comment by llkats** [comment]
:+1: :sushi: :fork_and_knife:

**Comment by tlhunter** [comment]
:+1:

**Comment by lakenen** [comment]
:white_check_mark:

**Comment by silvamerica** [comment]
:sake:

**Comment by junosuarez** [comment]
:fishing_pole_and_fish:

**Comment by junosuarez** [comment]
:fork_and_knife:

**Comment by lakenen** [comment]
:fish:
